# General settings.
BaseURL = "http://oakmachine.com/"
Title = "oakmachine"
MetaDataFormat = "toml"


# Syntax highlighting settings.
PygmentsUseClasses = true
PygmentsCodeFences = true


[author]
  name = "matt"


[permalinks]
  notes = "/:title/"


[indexes]
  tag = "tags"


[params]
  paginate = 10
  paginatePath = "page"
