baseurl = "http://notes.yosemitebandit.com/"
title = "notes"
languageCode = "en-us"
#disqusShortname = "your_disqus_shortname" # Optional, enable Disqus integration
MetaDataFormat = "toml"


[author]
  name = "matt"


[permalinks]
  notes = "/notes/:year/:month/:day/:title/"


[indexes]
  # Optional. Use if you want tags and lists.
  category = "categories"
  tag = "tags"


[params]
  # Used when a given page doesn't set its own.
  defaultDescription = "miscellany"
  defaultKeywords = "yes,sir,indeed"

  # Changes sidebar background and link/accent colours.
  # See below for more colour options.
  # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
  theme = "theme-base-10"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight = "sunburst"

  # Displays under the author name in the sidebar
  tagline = "quite"

  # Metadata used to drive integrations.
  #googleAuthorship = "Your Google+ profile ID"
  #googleAnalytics = "Your Google Analytics tracking code"
  #gravatarHash = "95f17d2a12df6a614b33282b42b48899"

  # Sidebar social links, avoid enabling too many of these if possible.
  # These should be full URLs.
  github = ""
  linkedin = ""
  googleplus = ""
  facebook = ""
  twitter = ""
