# General settings.
BaseURL = "https://oakmachine.com/"
Title = "oakmachine"
MetaDataFormat = "toml"
Theme = "pasture"


# Syntax highlighting settings.
PygmentsUseClasses = true
PygmentsCodeFences = true


[author]
  name = "matt"


[permalinks]
  notes = "/:title/"


[indexes]
  tag = "tags"


[params]
  paginate = 10
  paginatePath = "page"
  revisionHistoryUrl = "https://github.com/yosemitebandit/vebsite/commits/master/content/notes/"
