baseurl = "http://oak.yosemitebandit.com/"
title = "notes"
languageCode = "en-us"
MetaDataFormat = "toml"


[author]
  name = "matt"


[permalinks]
  notes = "/:title/"


[indexes]
  # Optional. Use if you want tags and lists.
  tag = "tags"


[params]
  # Changes sidebar background and link/accent colours.
  # See below for more colour options.
  # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
  theme = "theme-base-10"

  # Select a syntax highight.
  # Check the static/css/highlight directory for options.
  highlight = "tomorrow"

  # Metadata used to drive integrations.
  #googleAuthorship = "Your Google+ profile ID"
  #googleAnalytics = "Your Google Analytics tracking code"
