name = "pasture"
license = "MIT"
licenselink = "https://github.com/yosemitebandit/pasture/license.md"
description = "hyde-x, adjusted"
homepage = "https://github.com/yosemitebandit/pasture"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]

[author]
    name = "Matt Ball"
    homepage = "http://yosemitebandit.com"

# If Porting existing theme
[original]
    author =  "poole"
    homepage = "http://hyde.getpoole.com"
    repo = "https://github.com/poole/hyde"
