name = "pasture"
license = "MIT"
licenselink = "https://github.com/yosemitebandit/pasture/license.md"
description = "no frills blog"
homepage = "https://github.com/yosemitebandit/pasture"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]

[author]
    name = "Matt Ball"
    homepage = "http://yosemitebandit.com"
