[tool.poetry]
name = "drawings"
version = "0.1.0"
description = ""
authors = ["Matt Ball <matt.ball.2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
svgwrite = "^1.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
